packages:
  - 'packages/*'

catalog:
  '@rollup/plugin-babel': ^6.0.4
  '@shopify/babel-preset': ^25.0.2
  '@shopify/eslint-plugin': ^50.0.0
  '@shopify/typescript-configs': ^5.1.2
  '@types/node': ^24.10.13
  '@types/react': ^18.3.4
  '@types/react-dom': ^18.3.0
  'oxlint': ^1.49.0
  'react': ^18.2.0
  'react-dom': ^18.2.0
  'typescript': ^5.9.3
  'vite': ^6.4.3
  'vitest': ^4.0.0
  'vite-plugin-babel': ^1.3.0
  'vite-plugin-dts': ^4.5.3
  'vite-tsconfig-paths': ^5.1.4
